#!/bin/bash
# Generated by Clink - Development server script
# AI agent will modify this based on detected tech stack

cd /home/daytona/template

# Serve placeholder while AI agent sets up the project
python3 -m http.server "${PORT:-3000}" --bind "${HOST:-0.0.0.0}" --directory .clink
